### ISSUE TITLE
Query crashes

### ISSUE THREAD

**Issue by fededim** [streamx-co/try.elinq#7]
I have the following query in a webapi

```
        [HttpPost]
        public IList<Camera> GetCamerasOverview([FromBody] AuthoritiesTimestampRequest r)
        {
            var ris = ctx.Set<Camera>().Query((Camera c) =>
            {
                //var rowNum = AggregateBy(ROW_NUMBER()).OVER(ORDER(BY(c.Carriageway.Section.Authority.Name), BY(c.Distance)));

                var q = SELECT(c);  // ,rowNum.@as()
                FROM(c);
                WHERE(r.AuthorityIds.Contains(c.Carriageway.Section.AuthorityId));

                return q;
            }).Include(c => c.Carriageway).ThenInclude(cw => cw.Section).ThenInclude(s => s.Authority).AsNoTracking().ToList();

            return ris;
        }
```

yet it crashes with this exception:

```
System.ArgumentException: Expression of type 'System.Byte&' cannot be used for parameter of type 'System.Byte' of method 'Byte& Add[Byte](Byte ByRef, Int32)' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression[] arguments)
   at A.D.A(C , MethodBase )
   at Streamx.Linq.ExTree.ExpressionTree.A(D , MethodInfo )
   at Streamx.Linq.ExTree.ExpressionTree.Parse(Type delegateType, Expression targetExpression, MethodInfo method, IList`1 arguments)
   at A.H.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitInvocation(InvocationExpression node)
   at System.Linq.Expressions.InvocationExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at A.H.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitInvocation(InvocationExpression node)
   at System.Linq.Expressions.InvocationExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at A.H.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at A.H.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Streamx.Linq.SQL.EFCore.EFCoreExtensions.GetQuerySQL[TDelegate](IInfrastructure`1 source, TDelegate query, Object[]& params)
   at Streamx.Linq.SQL.EFCore.EFCoreExtensions.A[A,a](DbSet`1 , a )
   at Streamx.Linq.SQL.EFCore.EFCoreExtensions.Query[TEntity,TEntity1](DbSet`1 source, Func`2 query)
   at SincroADR_API.Controllers.CamerasController.GetCamerasOverview(AuthoritiesTimestampRequest r) in C:\Users\dimarco\source\repos\SincroADR\SincroADR_API\Controllers\CamerasController.cs:line 59
   at lambda_method113(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

If I remove the WHERE clause the query works perfectly (also the include). r.AuthorityIds is a List\<Int64\> and c.Carriageway.Section.AuthorityId is again Int64. I am using .Net 5 Web Api, EF Core 5.0.2 and the latest packages of your Streamx.Linq libraries, I can't understand why it reports an error on a byte. The query crashes with the same exception also if I remove all the includes, even though the queried entity does not have any byte properties.

If you need further information please let me know.

Federico

**Comment by kostat** [comment]
There are several issues with this query. 

- The most important is that elinq is a tool to write type safe SQL. So the expression must be a valid SQL. If your `Camera` entity references `Carriageway`, which references `Section` etc - all this should be expressed using appropriate `JOIN` constructs in SQL. Elinq wouldn't do it for you. In many cases this is not needed, because it can be done using LINQ, like you do with `Include()`. But if yes, it must be done explicitly.
- Another thing is that query parameters must be simple variables. So you need to write `var authorityIds = r.AuthorityIds;` outside the query and use `authorityIds` inside the query. This is the reason you get the exception above.

**Comment by kostat** [comment]
If you want to do the appropriate `JOIN`s, it would look similarly to this:
```cs
var ris = ctx.Set<Camera>().Query((Camera c, Carriageway cw, Section s) =>
{
    var q = SELECT(c);  // ,rowNum.@as()
    FROM(c).JOIN(cw).ON(c.Carriageway == cw).JOIN(s).ON(cw.Section == s);
    WHERE(r.AuthorityIds.Contains(c.Carriageway.Section.AuthorityId));

    return q;
})
```
