### ISSUE TITLE
Incorrect syntax near '`'.

### ISSUE THREAD

**Issue by TorreyGarland** [streamx-co/try.elinq#8]
new to Elinq.

Trying the basic select query example from an MVC Core 5 web application connecting to MsSql 2016 server.

```
IQueryable<FullName> query = _context.Set<FullName>()
				.Query((Customer customer, FullName alias) =>
				{
					var result = SELECT<FullName>(
						customer.FirstName.@as(alias.FirstName),
						customer.LastName.@as(alias.LastName));

					FROM(customer);
					//ORDER(BY(customer.Id));

					return result;
				});

			foreach (var customer in query)
				Console.WriteLine((customer.FirstName, customer.LastName));
```

The following exception thrown as soon as it tries to loop through results.

What am i missing, Chief?

```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near '`'.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
   at WebApplication12.Pages.IndexModel.OnGet() in C:\Users\torre\source\repos\WebApplication12\WebApplication12\Pages\Index.cshtml.cs:line 49
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.VoidHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.<InvokeHandlerMethodAsync>d__30.MoveNext()

  This exception was originally thrown at this call stack:
    [External Code]
    WebApplication12.Pages.IndexModel.OnGet() in Index.cshtml.cs
    [External Code]

```

**Comment by kostat** [comment]
Based in the backtick character error, I assume, that you use the MySQL version of the `ELinq.Configuration.RegisterVendorCapabilities()`. Since you are using SQL server you should use TransactSQL:
```cs
using Streamx.Linq.SQL.TransactSQL; //correct
using Streamx.Linq.SQL.MySQL; //incorrect
```
I would also suggest to output the SQL to the console, so you see it easily. See [LoggerFactory setup](https://github.com/streamx-co/try.elinq/blob/master/SqlServerTutorial/Program.cs) for example.

**Comment by TorreyGarland** [comment]
solved. thanks.

btw, using the exact loggingfactory example will give a warning:

```
public static readonly ILoggerFactory ConsoleLoggerFactory =
			LoggerFactory.Create(builder => {
				builder
					.AddFilter((category, level) =>
						category == DbLoggerCategory.Database.Command.Name && level >= LogLevel.Information)
					.AddSimpleConsole(options => options.ColorBehavior = Microsoft.Extensions.Logging.Console.LoggerColorBehavior.Disabled) // no warning.
					.AddConsole(options => options.DisableColors = true); // gives obsolete/deprecated warning
					;
			});
```

**Comment by kostat** [comment]
It's laudable you take the warnings seriously! The example targets .NET 3.1, where `AddSimpleConsole` did not exist, and this cannot be changed [yet] because [Try .NET](https://github.com/dotnet/try) does not support .NET 5.
